[[items]]
author = "James Stewart"
book = "Precalculus"
chapter_title = "Algebraic expressions"
chapter = 1.3

page_start = 25
page_exercises_start = 33

concepts_questions_interval_start = 1
concepts_questions_interval_end = 8

skills_questions_interval_start = 9
skills_questions_interval_end = 143

applications_questions_interval_start = 143
applications_questions_interval_end = 144

discussion_questions_interval_start = 145
discussion_questions_interval_end = 148

page_end = 35
